# This workflow will build and push a new container image to Amazon ECR
# The following information will need to be included in your Github secrets:
# - DOCKER_USERNAME: docker user name
# - DOCKER_PASSWORD: password or access token
# - DOCKER_REPOSITORY: your AWS region, ex: us-east-1, us-west-2...

on:
  push:
    branches:
      - docker-test2
    paths:
      - 'requirements.txt'
      - 'packages.R'
      - 'Dockerfile'
      - 'R/pkgs/**'

name: Deploy to DockerHub

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Generate Tags
      id: tags
      env:
        IMAGE_TAG_RUN: ${{ github.run_number }}
        IMAGE_TAG_REF: ${{ github.ref }}
      run: |
        echo "::set-output name=shashort::$(git log -1 --pretty=%h)"
        echo "::set-output name=reftag::${IMAGE_TAG_REF##*/}-r$IMAGE_TAG_RUN"

    - name: Build-Push
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: sperif/covidscenariopipeline
        tags: latest,${{steps.tags.outputs.shashort}},${{steps.tags.outputs.reftag}},${{ github.sha }}

